# Generated by Django 5.1.6 on 2025-03-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="box_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("60x40x40", "60x40x40"),
                    ("50x40x40", "50x40x40"),
                    ("45x45x45", "45x45x45"),
                    ("Custom", "Custom"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="pallet_weight",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-200", "0-200"),
                    ("200-300", "200-300"),
                    ("300-400", "300-400"),
                    ("400-500", "400-500"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
