# Generated by Django 5.1.6 on 2025-03-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_container_box_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name="order",
            name="containers",
        ),
        migrations.AddField(
            model_name="order",
            name="containers",
            field=models.ManyToManyField(to="orders.container"),
        ),
    ]
