# Generated by Django 4.2 on 2025-03-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_auto_20250320_0218"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
    ]
