# Generated by Django 5.1.6 on 2025-03-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_container_quantity_remove_order_containers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="box_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("60x40x40 см", "60x40x40 см"),
                    ("50x40x40 см", "50x40x40 см"),
                    ("45x45x45 см", "45x45x45 см"),
                    ("Другой размер", "Другой размер"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="container_type",
            field=models.CharField(
                choices=[("Коробка", "Коробка"), ("Паллета", "Паллета")], max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="pallet_weight",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-200 кг", "0-200 кг"),
                    ("200-300 кг", "200-300 кг"),
                    ("300-400 кг", "300-400 кг"),
                    ("400-500 кг", "400-500 кг"),
                    ("Другой вес", "Другой вес"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
