name: CD
on:
  push:
    branches:
      - main
jobs:

 deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            port: ${{ secrets.PORT }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
                set -e
                cd wms
                git switch main
                git pull